### ISSUE TITLE
Documentation is messed up

### ISSUE THREAD

**Issue by keflavich** [keflavich/image_registration#11]
Everything here has suffered from bitrot.  The sphinx auto-API stuff no longer works and locally I get junk like:

```
loading intersphinx inventory from http://docs.h5py.org/en/latest/objects.inv...
[autosummary] generating autosummary for: fourier_tools.rst, image_registration.FITS_tools.rst, image_registration.fft_tools.rst, image_registration.rst, image_registration.tests.rst, index.rst, spectral_xcorr.rst
[automodsumm] image_registration.rst: found 13 automodsumm entries to generate
Traceback (most recent call last):
  File "/Users/adam/repos/image_registration/astropy_helpers/astropy_helpers/sphinx/ext/automodsumm.py", line 489, in generate_automodsumm_docs
    template = template_env.get_template(tmplstr % doc.objtype)
  File "/Users/adam/anaconda/envs/astropy35/lib/python3.5/site-packages/jinja2/environment.py", line 812, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/adam/anaconda/envs/astropy35/lib/python3.5/site-packages/jinja2/environment.py", line 774, in _load_template
    cache_key = self.loader.get_source(self, name)[1]
  File "/Users/adam/anaconda/envs/astropy35/lib/python3.5/site-packages/Sphinx-1.3.5-py3.5.egg/sphinx/jinja2glue.py", line 159, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: autosummary/function.rst

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 28, in <module>
  File "/Users/adam/anaconda/envs/astropy35/lib/python3.5/site-packages/Sphinx-1.3.5-py3.5.egg/sphinx/application.py", line 189, in __init__
    self._init_builder(self.buildername)
  File "/Users/adam/anaconda/envs/astropy35/lib/python3.5/site-packages/Sphinx-1.3.5-py3.5.egg/sphinx/application.py", line 252, in _init_builder
    self.emit('builder-inited')
  File "/Users/adam/anaconda/envs/astropy35/lib/python3.5/site-packages/Sphinx-1.3.5-py3.5.egg/sphinx/application.py", line 508, in emit
    results.append(callback(self, *args))
  File "/Users/adam/repos/image_registration/astropy_helpers/astropy_helpers/sphinx/ext/automodsumm.py", line 268, in process_automodsumm_generation
    inherited_members=app.config.automodsumm_inherited_members)
  File "/Users/adam/repos/image_registration/astropy_helpers/astropy_helpers/sphinx/ext/automodsumm.py", line 491, in generate_automodsumm_docs
    template = template_env.get_template(tmplstr % 'base')
  File "/Users/adam/anaconda/envs/astropy35/lib/python3.5/site-packages/jinja2/environment.py", line 812, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/adam/anaconda/envs/astropy35/lib/python3.5/site-packages/jinja2/environment.py", line 774, in _load_template
    cache_key = self.loader.get_source(self, name)[1]
  File "/Users/adam/anaconda/envs/astropy35/lib/python3.5/site-packages/Sphinx-1.3.5-py3.5.egg/sphinx/jinja2glue.py", line 159, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: autosummary/base.rst
Sphinx Documentation subprocess failed with return code 1
```

**Comment by keflavich** [comment]
Looks like this solved itself.

**Comment by keflavich** [comment]
Nope, I lied, the problem is still there: there's no link from the frontpage to the `chi2_shift` document, but there are no errors being returned either...

**Comment by keflavich** [comment]
OK, solved by adding `scipy` as a requirement.
