### ISSUE TITLE
how to run and see the code in action

### ISSUE THREAD

**Issue by KingAlawaka** [keflavich/image_registration#22]
I want to register two images how can I do that. 
Kind of lost because of so many files... 
steps I followed

- according to the  REQUIREMENTS files install the all required packages 
- run the setup.py build 
- run the setup.py install 

which file I should execute to get an example or something to start with because when I run example files I am getting errors. 

Thanks in advance...Sry i am new :D

**Comment by keflavich** [comment]
See the examples in the example directory, especially https://github.com/keflavich/image_registration/blob/master/examples/Cross%20Correlation.ipynb

**Comment by KingAlawaka** [comment]
Any idea what went wrong... 
I have the same folder structure as in the git repo

> Traceback (most recent call last):
  File "Cross Correlation.py", line 16, in <module>
    import image_registration
  File "/home/king/.virtualenvs/facecourse-py3/lib/python3.5/site-packages/image_registration-0.2.5.dev0-py3.5.egg/image_registration/__init__.py", line 19, in <module>
    from . import tests
  File "/home/king/.virtualenvs/facecourse-py3/lib/python3.5/site-packages/image_registration-0.2.5.dev0-py3.5.egg/image_registration/tests/__init__.py", line 1, in <module>
    from .registration_testing import (upsample_ft_raw, make_offset_images,
  File "/home/king/.virtualenvs/facecourse-py3/lib/python3.5/site-packages/image_registration-0.2.5.dev0-py3.5.egg/image_registration/tests/registration_testing.py", line 11, in <module>
    from astropy.tests.helper import pytest
  File "/home/king/.virtualenvs/facecourse-py3/lib/python3.5/site-packages/astropy/tests/helper.py", line 14, in <module>
    import pytest
ImportError: No module named 'pytest'

>

**Comment by keflavich** [comment]
pytest is an external module; it looks like it is required at import time, even though it shouldn't be.  Just install it.
