### ISSUE TITLE
stumbling block in cross_correlation_shifts 

### ISSUE THREAD

**Issue by edeyejedi** [keflavich/image_registration#28]
Hi all, 
I'm no whizz at python so this could be a really easy solve, but i cant get past it. 
FYI - have update conda and all packages, double checked requirements and even pip installed from git
i have played around with the verbose/quiet flag to no avail. 
images are same size
code/error:
xoff, yoff = image_registration.cross_correlation_shifts(img1,img2)
print("Pixels shifted by: ", xoff, yoff)
Traceback (most recent call last):

  File "<ipython-input-3-1531713b25da>", line 3, in <module>
    xoff, yoff = image_registration.cross_correlation_shifts(img1,img2)

  File "C:\ProgramData\Anaconda3\envs\imreg\lib\site-packages\image_registration\cross_correlation_shifts.py", line 83, in cross_correlation_shifts
    ccorr = (correlate2d(image1,image2,quiet=quiet,**kwargs) / image1.size)

  File "C:\ProgramData\Anaconda3\envs\imreg\lib\site-packages\image_registration\fft_tools\correlate2d.py", line 42, in correlate2d
    return convolve(np.conjugate(im1), im2[::-1, ::-1], normalize_kernel=False,

  File "C:\ProgramData\Anaconda3\envs\imreg\lib\site-packages\astropy\nddata\decorators.py", line 176, in wrapper
    bound_args = signature(func).bind(data, *args, **kwargs)

  File "C:\ProgramData\Anaconda3\envs\imreg\lib\inspect.py", line 3025, in bind
    return self._bind(args, kwargs)

  File "C:\ProgramData\Anaconda3\envs\imreg\lib\inspect.py", line 3014, in _bind
    raise TypeError(

TypeError: got an unexpected keyword argument 'quiet'

hope someone can help

**Comment by edeyejedi** [comment]
Yup, that nailed it. 
Thanks
