### ISSUE TITLE
pip install image_registration not working 

### ISSUE THREAD

**Issue by SarinaKarmacharya** [keflavich/image_registration#37]
_not installing image_registration in python3.9.7 gives the following error:_ 

pip install image_registration==0.2.4

Collecting image_registration==0.2.4
  Using cached image_registration-0.2.4.tar.gz (2.8 MB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\sarin\anaconda3\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\sarin\\AppData\\Local\\Temp\\pip-install-d3zjegvk\\image-registration_715b4326f64f4b5ab32bbf237756eaea\\setup.py'"'"'; __file__='"'"'C:\\Users\\sarin\\AppData\\Local\\Temp\\pip-install-d3zjegvk\\image-registration_715b4326f64f4b5ab32bbf237756eaea\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\sarin\AppData\Local\Temp\pip-pip-egg-info-mbemx19c'
         cwd: C:\Users\sarin\AppData\Local\Temp\pip-install-d3zjegvk\image-registration_715b4326f64f4b5ab32bbf237756eaea\
    Complete output (1 lines):
    error in image_registration setup command: use_2to3 is invalid.
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/2a/6c/e1b96a53e6f3a6b2afa10623b1e5f9195a54bf07a7dd06ce0cc0da50b6ee/image_registration-0.2.4.tar.gz#sha256=a5416a2d91d3a8f43a089256ef3f959792fba69d03370b9d747120ea2dc0e77f (from https://pypi.org/simple/image-registration/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement image_registration==0.2.4 (from versions: 0.2, 0.2.1, 0.2.2, 0.2.3, 0.2.4)
ERROR: No matching distribution found for image_registration==0.2.4

**Comment by keflavich** [comment]
I pushed a new version (0.2.5) to pypi that should fix this

**Comment by SarinaKarmacharya** [comment]
when I do pip install image_registration then it still tries to install till version 0.2.4. Should I wait for a little longer to get the version 0.2.5?

Thank you

**Comment by keflavich** [comment]
my mistake, I left out the source distribution.  Try again?

**Comment by luzhenzheng** [comment]
same here

**Comment by keflavich** [comment]
@luzhenzheng  what's the current problem?  the source distribution for 0.2.5 is on pypi now and I have tested it successfully

**Comment by keflavich** [comment]
That error is because of cython, it has nothing to do with image_registration.  But, the `pyproject.toml` file included cython.  I've removed it.  Could you try installing from master?  e.g.,
```
pip install https://github.com/keflavich/image_registration/archive/refs/heads/master.zip
```

**Comment by SarinaKarmacharya** [comment]
Now getting this error
### 
Collecting https://github.com/keflavich/image_registration/archive/refs/heads/master.zip
  Downloading https://github.com/keflavich/image_registration/archive/refs/heads/master.zip
     \ 2.8 MB 2.1 MB/s
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\sarin\anaconda3\python.exe' 'C:\Users\sarin\anaconda3\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\sarin\AppData\Local\Temp\tmpwz3pprzs'
         cwd: C:\Users\sarin\AppData\Local\Temp\pip-req-build-6r0_hj16
    Complete output (36 lines):
    Traceback (most recent call last):
      File "C:\Users\sarin\anaconda3\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 349, in <module>
        main()
      File "C:\Users\sarin\anaconda3\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 331, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "C:\Users\sarin\anaconda3\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 151, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "C:\Users\sarin\AppData\Local\Temp\pip-build-env-lby_blsf\overlay\Lib\site-packages\setuptools\build_meta.py", line 188, in prepare_metadata_for_build_wheel
        self.run_setup()
      File "C:\Users\sarin\AppData\Local\Temp\pip-build-env-lby_blsf\overlay\Lib\site-packages\setuptools\build_meta.py", line 174, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 77, in <module>
        setup(use_scm_version={'write_to': os.path.join('image_registration', 'version.py'),
      File "C:\Users\sarin\AppData\Local\Temp\pip-build-env-lby_blsf\overlay\Lib\site-packages\setuptools\__init__.py", line 155, in setup
        return distutils.core.setup(**attrs)
      File "C:\Users\sarin\AppData\Local\Temp\pip-build-env-lby_blsf\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 109, in setup
        _setup_distribution = dist = klass(attrs)
      File "C:\Users\sarin\AppData\Local\Temp\pip-build-env-lby_blsf\overlay\Lib\site-packages\setuptools\dist.py", line 459, in __init__
        _Distribution.__init__(
      File "C:\Users\sarin\AppData\Local\Temp\pip-build-env-lby_blsf\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 293, in __init__
        self.finalize_options()
      File "C:\Users\sarin\AppData\Local\Temp\pip-build-env-lby_blsf\overlay\Lib\site-packages\setuptools\dist.py", line 852, in finalize_options
        ep(self)
      File "C:\Users\sarin\AppData\Local\Temp\pip-build-env-lby_blsf\overlay\Lib\site-packages\setuptools\dist.py", line 873, in _finalize_setup_keywords
        ep.load()(self, ep.name, value)
      File "C:\Users\sarin\AppData\Local\Temp\pip-build-env-lby_blsf\overlay\Lib\site-packages\setuptools_scm\integration.py", line 75, in version_keyword
        _assign_version(dist, config)
      File "C:\Users\sarin\AppData\Local\Temp\pip-build-env-lby_blsf\overlay\Lib\site-packages\setuptools_scm\integration.py", line 51, in _assign_version
        _version_missing(config)
      File "C:\Users\sarin\AppData\Local\Temp\pip-build-env-lby_blsf\overlay\Lib\site-packages\setuptools_scm\__init__.py", line 106, in _version_missing
        raise LookupError(
    LookupError: setuptools-scm was unable to detect version for C:\Users\sarin\AppData\Local\Temp\pip-req-build-6r0_hj16.

    Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.

    For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
    ----------------------------------------
WARNING: Discarding https://github.com/keflavich/image_registration/archive/refs/heads/master.zip. Command errored out with exit status 1: 'C:\Users\sarin\anaconda3\python.exe' 'C:\Users\sarin\anaconda3\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\sarin\AppData\Local\Temp\tmpwz3pprzs' Check the logs for full command output.
ERROR: Command errored out with exit status 1: 'C:\Users\sarin\anaconda3\python.exe' 'C:\Users\sarin\anaconda3\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\sarin\AppData\Local\Temp\tmpwz3pprzs' Check the logs for full command output.chr

**Comment by SarinaKarmacharya** [comment]
ok thank you very much for your help!! 
 it worked this time
```
pip install git+https://github.com/keflavich/image_registration.git#egg=image_registration

```

**Comment by luzhenzheng** [comment]
> @luzhenzheng what's the current problem? the source distribution for 0.2.5 is on pypi now and I have tested it successfully

Now it's working. Thx.
