### ISSUE TITLE
Error while installation

### ISSUE THREAD

**Issue by pradeep882006** [keflavich/image_registration#40]
Hi, 
I've been trying to install image_registration after a fresh installation of python (Anaconda distribution). It's been throwing up multiple errors. Surprisingly, I was able to do a fresh install on linux without any issues. Copying below the error that I'm getting:

WARNING: Discarding https://files.pythonhosted.org/packages/43/5d/b9f8cf74b11fe0fb9396ec97a902a0b3afc95ea16c2cf9a938c46d55710a/image_registration-0.2.3.tar.gz#sha256=473b298c72db127d861e3d7e91d369abb7a28b2ffbe04f827650247e6cf481d9 (from https://pypi.org/simple/image-registration/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached image_registration-0.2.2.tar.gz (54 kB)
    ERROR: Command errored out with exit status 1:
     command: 'E:\Users\Prad\anaconda3\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Loparo Lab\\AppData\\Local\\Temp\\pip-install-d2ibose6\\image-registration_6b52601e64ed40a1a4ff634ff6f9ca61\\setup.py'"'"'; __file__='"'"'C:\\Users\\Loparo Lab\\AppData\\Local\\Temp\\pip-install-d2ibose6\\image-registration_6b52601e64ed40a1a4ff634ff6f9ca61\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Loparo Lab\AppData\Local\Temp\pip-pip-egg-info-rvpo5nw3'
         cwd: C:\Users\Loparo Lab\AppData\Local\Temp\pip-install-d2ibose6\image-registration_6b52601e64ed40a1a4ff634ff6f9ca61\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Loparo Lab\AppData\Local\Temp\pip-install-d2ibose6\image-registration_6b52601e64ed40a1a4ff634ff6f9ca61\setup.py", line 8, in <module>
        import ah_bootstrap
    ModuleNotFoundError: No module named 'ah_bootstrap'

I've also tried installing using setup.py after downloading the github repo, without any luck. Any suggestions to resolve this will be greatly appreciated. Thanks. 

Best,
Pradeep

**Comment by keflavich** [comment]
how did you try to install this?  `ah_bootstrap` is not imported in the current version of setup.py

**Comment by pradeep882006** [comment]
> 
It was a regular pip install image_registration.

Thanks.

**Comment by keflavich** [comment]
try using `pip install --upgrade image_registration`.  You're using an old cached version, 0.2.2.  You should be using 0.2.5.
