### ISSUE TITLE
numpy1.23 arrays don't like lists of slices

### ISSUE THREAD

**Issue by joemasiero** [keflavich/image_registration#44]
I recently updated numpy (I know, my vault) and now the numpy arrays refuse to allow lists of slices.  Taking the example in the help() of chi2_shift:
```
from image_registration import chi2_shift
import numpy as np
rr = ((np.indices([100,100]) - np.array([50.,50.])[:,None,None])**2).sum(axis=0)**0.5
image = np.exp(-rr**2/(3.**2*2.)) * 20
shifted = np.roll(np.roll(image,12,0),5,1) + np.random.randn(100,100)
dx,dy,edx,edy = chi2_shift(image, shifted, upsample_factor='auto')

```
I get this error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/image_registration/chi2_shifts.py", line 202, in chi2_shift
    (yshifts_corrections,xshifts_corrections),chi2_ups = zoom.zoomnd(chi2,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/image_registration/fft_tools/zoom.py", line 172, in zoomnd
    return zoom_on_pixel(inp, middlepix, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/image_registration/fft_tools/zoom.py", line 101, in zoom_on_pixel
    outarr[ii] = outarr_d[dims]
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

```
numpy version: '1.23.1'
image_registration version: "0.2.5"

**Comment by keflavich** [comment]
This problem is fixed in the development version.
https://github.com/keflavich/image_registration/pull/42/files

I'll make a new release, though.

**Comment by keflavich** [comment]
New release is up:
https://pypi.org/project/image-registration/0.2.6/

**Comment by joemasiero** [comment]
Awesome, thanks for fixing that.  Checked, and my code is now working again.  And know I know to try tuple() when things break.
